// angularToDo/src/app/components/controllers/controllers.component.ts
import { Component, HostListener } from '@angular/core';
import { v4 as uuid } from 'uuid';
import { DataService } from 'src/app/services';

@Component({
  selector: 'controllers',
  templateUrl: './controllers.component.html',
  styleUrls: ['./controllers.component.scss']
})
export class ControllersComponent {
  private selectDate: moment.Moment | null = null;
  private newTodoName: string = '';
  private visiblePicker: boolean = false;

  constructor(private service: DataService){}

  get dataService(){
    return this.service;
  }

  get todoInput(){
    return this.newTodoName;
  }

  set todoInput(value: string){
    this.newTodoName = value;
  }

  get visibilityPicker(){
    return this.visiblePicker;
  }

  get day(){
    return this.selectDate;
  }

  set visibilityPicker(visible: boolean){
    this.visiblePicker = visible;
  }

  public onChangePickerTitle(day: moment.Moment){
    this.selectDate = day;
    this.onChangeVisibility();
  }

  @HostListener("document:click", ['$event'])
  public onDocumentClick(event: MouseEvent): void {
    const { target } = event;
    const isPicker: boolean = (target as Element)?.className === 'pickerDate';

    const parentNode = (target as HTMLElement)?.parentNode;
    const offParent = (target as HTMLElement)?.offsetParent;

    const isChild: boolean =
      offParent?.className?.includes('custom-calendar') ||
      (<Element>parentNode)?.className?.includes('custom-calendar');

    if ((!isPicker && !isChild) && this.visibilityPicker) this.onChangeVisibility();
  }

  public onChangeVisibility(): void {
    this.visibilityPicker = !this.visibilityPicker;
  }

  public onAdd(event: MouseEvent): void {
    if (this.todoInput && this.selectDate)
    this.dataService.addItem({
      id: uuid(),
      name: this.todoInput,
      date: this.selectDate.format('DD.MM.YYYY')
    });
    this.todoInput = '';
  }

  public onSort(sortType: string): void {
    if (!sortType) return;

    this.dataService.onSort(sortType);
  }
}


<div class="controllers">
  <div class="mainControllers">
    <input
      type='text'
      class="controllers__btn"
      placeholder="What should you do?"
      [(ngModel)]="todoInput"
    />
    <input
      class="pickerDate"
      type='button'
      [value]="day ? (day | moment) : 'pick date'"
      (click)="onChangeVisibility()"
    />
    <app-calendar
      (onChangeButtonTitle)="onChangePickerTitle($event)"
      [visibilityPicker]="visibilityPicker">
    </app-calendar>
  </div>
  <input
    type='button'
    class="controllers__btn"
    value='add'
    [disabled]="!todoInput"
    (click)="onAdd($event)"
  />
  <div class="sort-controllers">
    <input
      class="controllers__btn btn-sort past"
      type="button"
      value="past"
      (click)="onSort('past')"
    />
    <input
      class="btn-sort current"
      type="button"
      value="current"
      (click)="onSort('current')"
    />
    <input
      class="btn-sort future"
      type="button"
      value="future"
      (click)="onSort('future')"
    />
    <input
      class="btn-sort all"
      type="button"
      value="all"
      (click)="onSort('all')"
    />
  </div>
</div>

// client/src/Components/Controllers/index.jsx
import React from 'react';
import classnames from 'classnames';
import DatePicker from "react-date-picker";

class Controllers extends React.Component {

    state = {
		value: "",
		isValid: false,
        date: new Date()
      };
     
      handleChange = date => {
		const { value = "" } = this.state;
		const isValid = value && date;

        this.setState({ date, isValid });
	  };
	  
	  onAdd = event => {
		  const { isValid = false } = this.state;
		  const { onAdd = null } = this.props;
		  if (!isValid) return;
		  if (onAdd) onAdd(this.state);

		  this.setState({
			  value: "",
			  isValid: false,
			  date: new Date()
		  });
	  }

      onChange = event => {
		const { date = null } = this.state;
		const { target: { value = "" } = {} } = event || {};
		const isValid = value && date;
        this.setState({ value, isValid });
      }

    render(){
        const { date = new Date(), value, isValid = false } = this.state;
		const { onAdd = null, onSort = null } = this.props;

        return(
            <div className = 'controllers'>
				<input 
					className = 'controllers__btn'
					value = {value} 
					type = 'text' 
					placeholder = 'What should you do?' 
					onChange = {this.onChange} 
				/>
                <DatePicker
						className = 'controllers__btn'
                        value={date}
                        format={"d-M-yyyy"}
                        onChange={this.handleChange}
                />
				<input 
					className = 'controllers__btn'
					disabled = {!onAdd || !isValid} 
					onClick = {onAdd ? this.onAdd : null} 
					type = 'button'
					value = 'add' 
				/>
                <div className = 'sort-controllers'>
				 	<input 
						className = {classnames('controllers__btn', 'btn-sort', 'past')} 
						type = 'button' 
						value = 'past'
						onClick = {onSort}
					/>
				  	<input 
						  className = 'btn-sort current' 
						  type = 'button' 
						  value = 'current' 
						  onClick = {onSort}
					/>
				  	<input 
						  className = 'btn-sort future' 
						  type = 'button' 
						  value = 'future' 
						  onClick = {onSort}
					/>
					<input 
						className = 'btn-sort all' 
						type = 'button' 
						value = 'all' 
						onClick = {onSort}
					/>
                </div>
            </div>
        );
    }
};

export default Controllers;
