// PHP-ReactJS-todo/client/src/Components/Controllers/index.jsx
import React from 'react';
import DatePicker from "react-date-picker";


class Controllers extends React.Component {

    state = {
        date: new Date()
      };
     
      handleChange = date => {
          console.log(date);
        this.setState({
          date
        });
      };

    render(){
        const { date = new Date() } = this.state;
        const { onAdd = null } = this.props;
        return(
            <div className = 'controllers'>
                <input type = 'text' placeholder = 'What should you do?' />
                <DatePicker
                        value={date}
                        onChange={this.handleChange}
                />
                <input disabled = {!onAdd} onClick = {onAdd} type = 'button' value = 'add' />
            </div>
        )
    }
};

export default Controllers;

// angularToDo/src/app/controllers/controllers.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'controllers',
  templateUrl: './controllers.component.html',
  styleUrls: ['./controllers.component.scss']
})
export class ControllersComponent {
  private newTodoName: string;

  constructor() {
    this.newTodoName = '';
  }

  get todoInput(){
    return this.newTodoName;
  }

  set todoInput(value: string){
    this.newTodoName = value;
  }

  public onAdd(event: MouseEvent): void {
    this.todoInput = '';
  }

  public onSort(sortType: string): void {
    console.log(sortType);
  }

}


<div class="controllers">
  <input [(ngModel)]="todoInput" type='text' class="controllers__btn" placeholder="What should you do?" />
  <input type='button' class="controllers__btn" value='add' (click)="onAdd($event)" />
</div>
